version: '2.1'

services:
  janus-gateway:
    image: 'canyan/janus-gateway:master'
    restart: always
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "8188:8188" # websocket port
      - "7188:7188" # admin websocket port
      - "8088:8088" # http port
      - "8089:8089" # https port
      - "7088:7088" # admin http port
    volumes:
#      - "./config/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
#      - "./config/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
      - "./config/janus.transport.websockets.jcfg:/usr/local/etc/janus/janus.transport.websockets.jcfg"
      - "./config/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg"

  web_demo:
    user: "root"
    image: httpd:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./web:/usr/local/apache2/htdocs